# Generated by Django 4.2.9 on 2024-06-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine_order',
            old_name='machine_name',
            new_name='machine',
        ),
        migrations.RenameField(
            model_name='machine_order',
            old_name='order_number',
            new_name='order',
        ),
    ]
