# Generated by Django 4.2.9 on 2024-06-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0048_alter_order_states_name'),
        ('machines', '0002_rename_machine_name_machine_order_machine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('GTO(1) طباعة ربع', 'GTO(1) طباعة ربع'), ('SM(2) طباعة ربع', 'SM(2) طباعة ربع'), ('SM(5) طباعة ربع', 'SM(5) طباعة ربع'), ('SORM طباعة نص', 'SORM طباعة نص'), ('SM(2) طباعة نص', 'SM(2) طباعة نص'), ('SM طباعة فرخ', 'SM طباعة فرخ'), ('CD(5) طباعة فرخ', 'CD(5) طباعة فرخ'), ('DIE 46 تكسير', 'DIE 46 تكسير'), ('DIE 57 تكسير', 'DIE 57 تكسير'), ('BOBST تكسير', 'BOBST تكسير'), ('PACTEK 85 تلزيق', 'PACTEK 85 تلزيق'), ('PACTEK 65 تلزيق', 'PACTEK 65 تلزيق'), ('FG  تلزيق', 'FG  تلزيق'), ('SBL  تلزيق', 'SBL  تلزيق')], max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine_order',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
            preserve_default=False,
        ),
    ]
