# Generated by Django 4.2.9 on 2024-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_machine_machine_name_alter_machine_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_order',
            name='machines_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_name',
            field=models.CharField(blank=True, choices=[('تجهيز ورق', 'تجهيز ورق'), ('GTO(1) طباعة ربع', 'GTO(1) طباعة ربع'), ('SM(2) طباعة ربع', 'SM(2) طباعة ربع'), ('SM(5) طباعة ربع', 'SM(5) طباعة ربع'), ('SORM طباعة نص', 'SORM طباعة نص'), ('SM(2) طباعة نص', 'SM(2) طباعة نص'), ('SM طباعة فرخ', 'SM طباعة فرخ'), ('CD(5) طباعة فرخ', 'CD(5) طباعة فرخ'), ('سلوفان', 'سلوفان'), ('خدمات طباعة ورنيش/يوفي', 'خدمات طباعة ورنيش/يوفي'), ('خدمات طباعة خارجي', 'خدمات طباعة خارجي'), ('DIE 46 تكسير', 'DIE 46 تكسير'), ('DIE 57 تكسير', 'DIE 57 تكسير'), ('BOBST تكسير', 'BOBST تكسير'), ('التسليك و التنظيف', 'التسليك و التنظيف'), ('PACTEK 85 تلزيق', 'PACTEK 85 تلزيق'), ('PACTEK 65 تلزيق', 'PACTEK 65 تلزيق'), ('FG  تلزيق', 'FG  تلزيق'), ('SBL  تلزيق', 'SBL  تلزيق'), ('تلزيق يدوي', 'تلزيق يدوي'), ('تجليد', 'تجليد'), ('قص بضاعة منتهية', 'قص بضاعة منتهية'), ('تلزيق خارجي', 'تلزيق خارجي')], max_length=200, null=True, unique=True),
        ),
    ]
