# Generated by Django 4.2.9 on 2024-06-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_machine_order_machines_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_order',
            name='machines_number',
        ),
    ]
