# Generated by Django 4.2.9 on 2024-06-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_remove_machine_order_machines_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_order',
            name='machine',
        ),
        migrations.CreateModel(
            name='MachineOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machines_number', models.IntegerField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine')),
                ('machine_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.machine_order')),
            ],
        ),
        migrations.AddField(
            model_name='machine_order',
            name='machines',
            field=models.ManyToManyField(blank=True, through='machines.MachineOrder', to='machines.machine'),
        ),
    ]
