# Generated by Django 4.2.9 on 2024-06-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_remove_machine_order_machine_machineorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_order',
            name='machines',
        ),
        migrations.AddField(
            model_name='machine_order',
            name='machine',
            field=models.ManyToManyField(to='machines.machine'),
        ),
        migrations.DeleteModel(
            name='MachineOrder',
        ),
    ]
