# Generated by Django 4.0 on 2021-12-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=50, unique=True)),
                ('Created_Dt', models.DateTimeField(auto_now_add=True)),
                ('Contact_Name', models.CharField(max_length=50)),
                ('Contact_Phone', models.CharField(max_length=50)),
                ('Contact_Email', models.EmailField(max_length=254)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector_Name', models.CharField(max_length=50, unique=True)),
                ('Sector_Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=300, unique=True)),
                ('Created_Dt', models.DateTimeField(auto_now_add=True)),
                ('Product_Details', models.TextField(max_length=4000)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='auth.user')),
                ('Product_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_Dt', models.DateTimeField(auto_now_add=True)),
                ('Order_Details', models.TextField(max_length=4000)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='auth.user')),
                ('Order_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='Work_Orders.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Customer_Sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customers', to='Work_Orders.sector'),
        ),
    ]
