# Generated by Django 4.0 on 2021-12-18 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Work_Orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to='Work_Orders.customer')),
                ('Account_Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Accounts', to='auth.user')),
            ],
        ),
    ]
