# Generated by Django 4.0 on 2022-02-10 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Sector', to='Work_Orders.sector'),
            preserve_default=False,
        ),
    ]
