# Generated by Django 4.0 on 2022-02-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0003_product_product_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.sector'),
        ),
    ]
