# Generated by Django 4.0 on 2022-02-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0004_alter_product_product_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(max_length=300),
        ),
    ]
