# Generated by Django 4.0 on 2022-02-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0005_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='Sector_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
