# Generated by Django 4.0 on 2022-02-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0006_sector_sector_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='Sector_code',
            new_name='Sector_Code',
        ),
    ]
