# Generated by Django 4.0 on 2022-02-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0007_rename_sector_code_sector_sector_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='Sector_Code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
