# Generated by Django 4.0.2 on 2022-06-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0009_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
