# Generated by Django 4.0.2 on 2022-06-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0010_alter_customer_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerss_code',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
