# Generated by Django 4.0.2 on 2022-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0011_customer_customerss_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_code',
        ),
    ]
