# Generated by Django 4.0.2 on 2022-06-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0012_remove_customer_customer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customerss_code',
            new_name='customer_code',
        ),
    ]
