# Generated by Django 4.0.2 on 2022-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0013_rename_customerss_code_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
