# Generated by Django 4.0.2 on 2022-06-28 13:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0014_alter_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aftar_Print_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_aftar_print_services_type', models.CharField(choices=[('ورنيش مائى ', 'ورنيش مائى '), ('يوفى ', 'يوفى '), ('سلوفان ', 'سلوفان '), ('سبوت يوفى  ', 'سبوت يوفى  '), ('بصمه ', 'بصمه '), ('مضلع  ', 'مضلع  ')], max_length=100)),
                ('pro_aftar_print_services_detals', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crushing_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_crushing_data_type', models.CharField(blank=True, choices=[('تام', 'تام'), ('شباك', 'شباك'), ('كوفراج', 'كوفراج'), ('ريجة', 'ريجة'), ('فورم', 'فورم')], max_length=100, null=True)),
                ('pro_crushing_data_detals', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design_And_Printing_Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_design_source', models.CharField(choices=[('المطبعه ', 'المطبعه '), ('العميل ', 'العميل ')], max_length=20)),
                ('pro_design_type', models.CharField(choices=[('جديد ', 'جديد '), ('قديم مع تعديل البيانات  ', 'قديم مع تعديل البيانات  '), ('قديم مع تعديل التصميم  ', 'قديم مع تعديل التصميم  ')], max_length=70)),
                ('pro_old_execution', models.BooleanField(choices=[('اعدام القديم  ', 'اعدام القديم  ')], default=False)),
                ('tinted_colors1', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tinted_colors2', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tinted_colors3', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tinted_colors4', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tinted_colors5', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('tinted_colors6', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('product_color', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cyan', 'C'), ('Magenta', 'M'), ('Key', 'K'), ('yellow', 'Y')], default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finished_product_and_packing_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_finished_product_and_packing_data_type', models.CharField(blank=True, choices=[('باندات ورق', 'باندات ورق'), ('استيك', 'استيك')], max_length=30, null=True)),
                ('pro_Finished_product_and_packing_data_Baku', models.CharField(blank=True, choices=[('ورق', 'ورق'), ('اكياس', 'اكياس'), ('شرنك', 'شرنك')], max_length=100, null=True)),
                ('pro_finished_product_and_packing_data_detals', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gluing_And_Binding_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_Gluing_And_Binding_Data_type', models.CharField(blank=True, choices=[('تلزيق آلى', 'تلزيق آلى'), ('تلزيق يدوى', 'تلزيق يدوى'), ('تلزيق استرلون', 'تلزيق استرلون'), ('تجليد', 'تجليد')], max_length=100, null=True)),
                ('pro_Gluing_And_Binding_Data_detals', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pro_Paper_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_paper_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Dicription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Description_type', models.TextField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Allowable_increase',
            field=models.BooleanField(choices=[('حسب امر الشغل ', 'حسب امر الشغل '), ('10% بحد اقصى ', '10% بحد اقصى ')], default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Code',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product_MyCode',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Product_height',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_width',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_avrage_prdect_ammount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Name',
            field=models.CharField(max_length=300, verbose_name='اسم النتج'),
        ),
        migrations.CreateModel(
            name='Paper_Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_paper_gram', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('fiber_direction', models.BooleanField(choices=[('ضرورية ', '=ضرورية '), ('غير ضرورىة', 'غير ضرورىة')], default=False)),
                ('pro_paper_type', models.ManyToManyField(blank=True, related_name='Paper_Specification', to='Work_Orders.Pro_Paper_Type')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Aftar_Print_Services',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Aftar_Print_Services'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Crushing_Data',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Crushing_Data'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Design_And_Printing_Specifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Finished_product_and_packing_data',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Finished_product_and_packing_data'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Gluing_And_Binding_Data',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Gluing_And_Binding_Data'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dicription',
            field=models.ManyToManyField(blank=True, related_name='Product_Description', to='Work_Orders.Product_Dicription'),
        ),
    ]
