# Generated by Django 4.0.2 on 2022-06-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0015_aftar_print_services_crushing_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_paper_specification',
            field=models.ManyToManyField(blank=True, related_name='Products', to='Work_Orders.Paper_Specification'),
        ),
    ]
