# Generated by Django 4.0.2 on 2022-06-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0016_product_product_paper_specification'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_and_printing_specifications',
            name='attachments_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d'),
        ),
    ]
