# Generated by Django 4.0.2 on 2022-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0017_design_and_printing_specifications_attachments_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=models.CharField(choices=[('اعدام القديم  ', 'اعدام القديم  ')], max_length=70),
        ),
        migrations.AlterField(
            model_name='paper_specification',
            name='fiber_direction',
            field=models.CharField(blank=True, choices=[('ضرورية ', 'ضرورية '), ('غير ضرورىة', 'غير ضرورىة')], default=None, max_length=80, null=True),
        ),
    ]
