# Generated by Django 4.0.2 on 2022-06-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0018_alter_design_and_printing_specifications_pro_old_execution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=models.CharField(choices=[('حسب امر الشغل ', 'حسب امر الشغل '), ('10% بحد اقصى ', '10% بحد اقصى ')], default='حسب امر الشغل ', max_length=50),
        ),
    ]
