# Generated by Django 4.0.2 on 2022-06-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0019_alter_product_product_allowable_increase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_dicription',
        ),
        migrations.AddField(
            model_name='product',
            name='product_dicription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Description', to='Work_Orders.product_dicription'),
        ),
    ]
