# Generated by Django 4.0.2 on 2022-06-30 16:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0020_remove_product_product_dicription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب امر الشغل ', 'حسب امر الشغل '), ('10% بحد اقصى ', '10% بحد اقصى ')], default='حسب امر الشغل ', max_length=50),
        ),
    ]
