# Generated by Django 4.0.2 on 2022-07-02 10:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0021_alter_product_product_allowable_increase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اعدام القديم  ', 'اعدام القديم  ')], max_length=70),
        ),
    ]
