# Generated by Django 4.0.2 on 2022-07-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0022_alter_design_and_printing_specifications_pro_old_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_and_printing_specifications',
            name='number_of_sides',
            field=models.CharField(choices=[('وجه', 'وجه'), ('وجهان', 'وجهان'), ('قلاب', 'قلاب')], default='وجه', max_length=10),
        ),
    ]
