# Generated by Django 4.0.2 on 2022-07-02 12:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0023_design_and_printing_specifications_number_of_sides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftar_print_services',
            name='pro_aftar_print_services_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ورنيش مائى ', 'ورنيش مائى '), ('يوفى ', 'يوفى '), ('سلوفان ', 'سلوفان '), ('سبوت يوفى  ', 'سبوت يوفى  '), ('بصمه ', 'بصمه '), ('مضلع  ', 'مضلع  ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='crushing_data',
            name='pro_crushing_data_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تام', 'تام'), ('شباك', 'شباك'), ('كوفراج', 'كوفراج'), ('ريجة', 'ريجة'), ('فورم', 'فورم')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gluing_and_binding_data',
            name='pro_Gluing_And_Binding_Data_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تلزيق آلى', 'تلزيق آلى'), ('تلزيق يدوى', 'تلزيق يدوى'), ('تلزيق استرلون', 'تلزيق استرلون'), ('تجليد', 'تجليد')], max_length=100, null=True),
        ),
    ]
