# Generated by Django 4.0.2 on 2022-07-04 14:01

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0024_alter_aftar_print_services_pro_aftar_print_services_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_specification',
            name='pro_paper_type',
        ),
        migrations.AddField(
            model_name='paper_specification',
            name='pro_paper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paper_Specification', to='Work_Orders.pro_paper_type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب امر الشغل ', 'حسب امر الشغل '), ('10% بحد اقصى ', '10% بحد اقصى ')], default='حسب امر الشغل ', max_length=50, verbose_name='الزياده النسموح بها  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Code',
            field=models.CharField(max_length=50, unique=True, verbose_name=' كود العميل '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_height',
            field=models.FloatField(blank=True, null=True, verbose_name='الارتفاع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_length',
            field=models.FloatField(verbose_name='الطول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_width',
            field=models.FloatField(verbose_name='العرض'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_avrage_prdect_ammount',
            field=models.IntegerField(default=0, verbose_name='  الكميه المتوقعه  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_dicription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Description', to='Work_Orders.product_dicription', verbose_name='وصف المنتج'),
        ),
    ]
