# Generated by Django 4.0.2 on 2022-07-05 10:10

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0025_remove_paper_specification_pro_paper_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design_and_printing_specifications',
            name='pro_design_ditals',
            field=models.CharField(default='', max_length=200, verbose_name='تفاصيل التصميم '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aftar_print_services',
            name='pro_aftar_print_services_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ورنيش مائى ', 'ورنيش مائى '), ('يوفى ', 'يوفى '), ('سلوفان ', 'سلوفان '), ('سبوت يوفى  ', 'سبوت يوفى  '), ('بصمه ', 'بصمه '), ('مضلع  ', 'مضلع  ')], max_length=100, verbose_name='نوع الخدمه '),
        ),
        migrations.AlterField(
            model_name='crushing_data',
            name='pro_crushing_data_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تام', 'تام'), ('شباك', 'شباك'), ('كوفراج', 'كوفراج'), ('ريجة', 'ريجة'), ('فورمة', 'فورمة')], max_length=100, null=True, verbose_name='نوع الخدمه '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='attachments_file',
            field=models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/%d', verbose_name='ارفاق ملف معتمد  '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='number_of_sides',
            field=models.CharField(choices=[('وجه', 'وجه'), ('وجهان', 'وجهان'), ('قلاب', 'قلاب')], default='وجه', max_length=10, verbose_name='عدد الاوجه '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_source',
            field=models.CharField(choices=[('المطبعه ', 'المطبعه '), ('العميل ', 'العميل ')], max_length=20, verbose_name='مصدر التصميم '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_type',
            field=models.CharField(choices=[('جديد ', 'جديد '), ('تعديل   ', 'تعديل   '), ('قديم   ', 'قديم   ')], max_length=70, verbose_name='نوع التصميم '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اعدام القديم  ', 'اعدام القديم  ')], max_length=70, verbose_name=' '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cyan', 'C'), ('Magenta', 'M'), ('Key', 'K'), ('yellow', 'Y')], default=None, max_length=50, null=True, verbose_name='الالون '),
        ),
        migrations.AlterField(
            model_name='finished_product_and_packing_data',
            name='pro_Finished_product_and_packing_data_Baku',
            field=models.CharField(blank=True, choices=[('ورق', 'ورق'), ('اكياس', 'اكياس'), ('شرنك', 'شرنك')], max_length=100, null=True, verbose_name='الباكو'),
        ),
        migrations.AlterField(
            model_name='finished_product_and_packing_data',
            name='pro_finished_product_and_packing_data_type',
            field=models.CharField(blank=True, choices=[('باندات ورق', 'باندات ورق'), ('استيك', 'استيك')], max_length=30, null=True, verbose_name='المنتج النهائي '),
        ),
        migrations.AlterField(
            model_name='gluing_and_binding_data',
            name='pro_Gluing_And_Binding_Data_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تلزيق آلى', 'تلزيق آلى'), ('تلزيق يدوى', 'تلزيق يدوى'), ('تلزيق استالون', 'تلزيق استالون'), ('تجليد', 'تجليد')], max_length=100, null=True, verbose_name='نوع الخدمه '),
        ),
        migrations.AlterField(
            model_name='paper_specification',
            name='fiber_direction',
            field=models.CharField(blank=True, choices=[('ضرورية ', 'ضرورية '), ('غير ضرورىة', 'غير ضرورىة')], default=None, max_length=80, null=True, verbose_name='اتجاه الالياف '),
        ),
        migrations.AlterField(
            model_name='paper_specification',
            name='pro_paper_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Paper_Specification', to='Work_Orders.pro_paper_type', verbose_name='نوع الورق '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب امر الشغل ', 'حسب امر الشغل '), ('10% بحد اقصى ', '10% بحد اقصى ')], default='حسب امر الشغل ', max_length=50, verbose_name='الزياده المسموح بها  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_width',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_avrage_prdect_ammount',
            field=models.IntegerField(default=0),
        ),
    ]
