# Generated by Django 4.0.2 on 2022-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0026_design_and_printing_specifications_pro_design_ditals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_ditals',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تفاصيل التصميم '),
        ),
    ]
