# Generated by Django 4.0.2 on 2022-07-05 16:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0027_alter_design_and_printing_specifications_pro_design_ditals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_source',
            field=models.CharField(blank=True, choices=[('المطبعه ', 'المطبعه '), ('العميل ', 'العميل ')], default=None, max_length=20, null=True, verbose_name='مصدر التصميم '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('اعدام القديم  ', 'اعدام القديم  ')], max_length=70, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_avrage_prdect_ammount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='المتوسط'),
        ),
    ]
