# Generated by Django 4.0 on 2022-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0029_alter_design_and_printing_specifications_pro_design_ditals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Ordered_Supply',
            field=models.CharField(default='', max_length=50, verbose_name='أمر توريد '),
            preserve_default=False,
        ),
    ]
