# Generated by Django 4.0 on 2022-08-30 11:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0030_product_product_ordered_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Customer_code_edite',
            field=models.CharField(default='', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aftar_print_services',
            name='pro_aftar_print_services_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ورنيش مائى', 'ورنيش مائى'), ('يوفى', 'يوفى'), ('سلوفان', 'سلوفان'), ('سبوت يوفى', 'سبوت يوفى'), ('بصمه', 'بصمه'), ('مضلع', 'مضلع')], max_length=100, verbose_name='نوع الخدمه '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('اعدام القديم ', 'اعدام القديم ')], default=None, max_length=70, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب امر الشغل', 'حسب امر الشغل'), ('10% بحد اقصى', '10% بحد اقصى')], default='حسب امر الشغل ', max_length=50, verbose_name='الزياده المسموح بها  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_Ordered_Supply',
            field=models.CharField(max_length=50, verbose_name='أمر توريد'),
        ),
    ]
