# Generated by Django 4.0 on 2022-09-10 11:19

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0031_customer_customer_code_edite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('اعدام القديم', 'اعدام القديم')], default=None, max_length=70, null=True, verbose_name=''),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
