# Generated by Django 4.0 on 2022-09-19 10:15

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0032_alter_design_and_printing_specifications_pro_old_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ممثل العميل'),
        ),
        migrations.AlterField(
            model_name='aftar_print_services',
            name='pro_aftar_print_services_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ورنيش مائى', 'ورنيش مائى'), ('يوفى', 'يوفى'), ('سلوفان', 'سلوفان'), ('سبوت يوفى', 'سبوت يوفى'), ('بصمه', 'بصمه'), ('مضلع', 'مضلع')], default=None, max_length=100, null=True, verbose_name='نوع الخدمه '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact_Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cyan', 'C'), ('Magenta', 'M'), ('yellow', 'Y'), ('Key', 'K')], default=None, max_length=50, null=True, verbose_name='الالون '),
        ),
    ]
