# Generated by Django 4.0 on 2022-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0033_product_customer_representative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_type',
            field=models.CharField(choices=[('جديد ', 'جديد '), ('تعديل', 'تعديل'), ('قديم', 'قديم')], max_length=70, verbose_name='نوع التصميم '),
        ),
    ]
