# Generated by Django 4.0 on 2022-09-20 12:16

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0035_alter_aftar_print_services_pro_aftar_print_services_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_representative',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('د/عمروالباز', 'د/عمروالباز'), ('ا/عمرو احمد', 'ا/عمرو احمد'), ('م/كريم عبد الغنى ', 'م/كريم عبد الغنى ')], default='', max_length=100, verbose_name='ممثل  العميل'),
            preserve_default=False,
        ),
    ]
