# Generated by Django 4.0 on 2022-09-24 09:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0036_alter_product_customer_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب امر الشغل', 'حسب امر الشغل'), ('10% بحد اقصى', '10% بحد اقصى')], default='حسب امر الشغل ', max_length=50, verbose_name='*الزياده المسموح بها  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_representative',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('د/عمروالباز', 'د/عمروالباز'), ('ا/عمرو احمد', 'ا/عمرو احمد'), ('م/كريم عبد الغنى', 'م/كريم عبد الغنى'), ('اخرى', 'اخرى')], max_length=100, verbose_name='ممثل  العميل'),
        ),
    ]
