# Generated by Django 4.0 on 2022-09-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0037_alter_product_product_allowable_increase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_avrage_prdect_ammount',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='المتوسط'),
        ),
    ]
