# Generated by Django 4.0 on 2022-10-04 14:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0040_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_source',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('المطبعه ', 'المطبعه '), ('العميل ', 'العميل ')], default=None, max_length=20, null=True, verbose_name='مصدر التصميم '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('جديد', 'جديد'), ('تعديل', 'تعديل'), ('قديم', 'قديم')], default=None, max_length=70, null=True, verbose_name='نوع التصميم '),
        ),
    ]
