# Generated by Django 4.0 on 2022-10-04 14:43

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0041_alter_design_and_printing_specifications_pro_design_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_source',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('المطبعه', 'المطبعه'), ('العميل', 'العميل')], default=None, max_length=20, null=True, verbose_name='مصدر التصميم '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Cyan', 'C'), ('Magenta', 'M'), ('yellow', 'Y'), ('Key', 'K')], default=None, max_length=50, null=True, verbose_name='الالون'),
        ),
    ]
