# Generated by Django 4.0 on 2022-10-04 14:50

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0042_alter_design_and_printing_specifications_pro_design_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='number_of_sides',
            field=models.CharField(choices=[('وجه', 'وجه'), ('وجهين', 'وجهين'), ('قلاب', 'قلاب')], default='وجه', max_length=10, verbose_name='عدد الاوجه '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_source',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('المطبعة', 'المطبعة'), ('العميل', 'العميل')], default=None, max_length=20, null=True, verbose_name='مصدر التصميم '),
        ),
        migrations.AlterField(
            model_name='paper_specification',
            name='fiber_direction',
            field=models.CharField(blank=True, choices=[('ضرورية', 'ضرورية'), ('غير ضرورىة', 'غير ضرورىة')], default=None, max_length=80, null=True, verbose_name='اتجاه الالياف '),
        ),
    ]
