# Generated by Django 4.0 on 2022-10-06 13:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0044_alter_aftar_print_services_pro_aftar_print_services_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftar_print_services',
            name='pro_aftar_print_services_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('قص', 'قص'), ('ورنيش', 'ورنيش'), ('يوفى', 'يوفى'), ('سلوفان', 'سلوفان'), ('سبوت يوفى', 'سبوت يوفى'), ('بصمة', 'بصمة'), ('مضلع', 'مضلع')], default=None, max_length=100, null=True, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='number_of_sides',
            field=models.CharField(choices=[('وجه', 'وجه'), ('وجهين', 'وجهين'), ('قلاب', 'قلاب')], default='وجه', max_length=10, verbose_name='عدد الأوجه '),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_old_execution',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('إعدام القديم', 'إعدام القديم')], default=None, max_length=70, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='finished_product_and_packing_data',
            name='pro_Finished_product_and_packing_data_Baku',
            field=models.CharField(blank=True, choices=[('ورق', 'ورق'), ('أكياس', 'أكياس'), ('شرنك', 'شرنك')], max_length=100, null=True, verbose_name='الباكو'),
        ),
        migrations.AlterField(
            model_name='finished_product_and_packing_data',
            name='pro_finished_product_and_packing_data_type',
            field=models.CharField(blank=True, choices=[('باندات ورق', 'باندات ورق'), ('أستيك', 'أستيك')], max_length=30, null=True, verbose_name='المنتج النهائي '),
        ),
        migrations.AlterField(
            model_name='gluing_and_binding_data',
            name='pro_Gluing_And_Binding_Data_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('تلزيق آلى', 'تلزيق آلى'), ('تلزيق يدوي', 'تلزيق يدوي'), ('تلزيق إستالون', 'تلزيق إستالون'), ('تجليد', 'تجليد')], max_length=100, null=True, verbose_name='نوع الخدمة '),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Allowable_increase',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('حسب أمر الشغل', 'حسب أمر الشغل'), ('10% بحد أقصى', '10% بحد أقصى')], default='حسب امر الشغل ', max_length=50, verbose_name='*الزيادة المسموح بها  '),
        ),
    ]
