# Generated by Django 4.0 on 2023-04-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0045_alter_aftar_print_services_pro_aftar_print_services_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Created_Dt',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Created_Dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
