# Generated by Django 4.0 on 2023-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0047_alter_design_and_printing_specifications_tinted_colors1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors1',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors2',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors3',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors4',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors5',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='tinted_colors6',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
