# Generated by Django 4.0 on 2023-08-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0048_alter_design_and_printing_specifications_tinted_colors1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='Sector_Code',
            field=models.CharField(max_length=2),
        ),
    ]
