# Generated by Django 4.0 on 2023-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0049_alter_sector_sector_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='Sector_Name',
            field=models.CharField(max_length=50),
        ),
    ]
