# Generated by Django 4.0 on 2023-08-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0050_alter_sector_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='Sector_Code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='Sector_Name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
