# Generated by Django 4.0 on 2023-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0051_alter_sector_sector_code_alter_sector_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=9),
        ),
    ]
