# Generated by Django 4.0 on 2023-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0054_alter_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
