# Generated by Django 4.0 on 2023-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0055_alter_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Ordered_Supply',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='أمر توريد'),
        ),
    ]
