# Generated by Django 4.0 on 2023-08-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0057_alter_product_product_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Aftar_Print_Services',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Aftar_Print_Services',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.aftar_print_services'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Crushing_Data',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Crushing_Data',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.crushing_data'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.design_and_printing_specifications'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Finished_product_and_packing_data',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Finished_product_and_packing_data',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.finished_product_and_packing_data'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_Gluing_And_Binding_Data',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Gluing_And_Binding_Data',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.gluing_and_binding_data'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_paper_specification',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_paper_specification',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.paper_specification'),
            preserve_default=False,
        ),
    ]
