# Generated by Django 4.0 on 2023-08-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0059_alter_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_MyCode',
            field=models.CharField(max_length=50),
        ),
    ]
