# Generated by Django 4.0 on 2023-08-14 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0060_alter_product_product_mycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Aftar_Print_Services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.aftar_print_services'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Crushing_Data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.crushing_data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.design_and_printing_specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Finished_product_and_packing_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.finished_product_and_packing_data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Gluing_And_Binding_Data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.gluing_and_binding_data'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_MyCode',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_paper_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.paper_specification'),
        ),
    ]
