# Generated by Django 4.0 on 2023-08-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0061_alter_customer_customer_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Details',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=50, null=True),
        ),
    ]
