# Generated by Django 4.0 on 2023-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0062_remove_product_product_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_status',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Details',
            field=models.TextField(default='', max_length=4000),
            preserve_default=False,
        ),
    ]
