# Generated by Django 4.0 on 2023-09-16 11:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0063_remove_product_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_representative',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('د/عمروالباز', 'د/عمروالباز'), ('ا/عمرو احمد', 'ا/عمرو احمد'), ('م/كريم عبد الغنى', 'م/كريم عبد الغنى'), ('أخرى', 'أخرى')], default='أخرى', max_length=100, verbose_name='ممثل  العميل'),
        ),
    ]
