# Generated by Django 4.0 on 2023-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0065_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Details',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
