# Generated by Django 4.2.9 on 2024-01-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0066_alter_product_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Contact_Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Contact_Phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
