# Generated by Django 4.2.9 on 2024-01-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0067_alter_customer_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Customer_code_edite',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
