# Generated by Django 4.2.9 on 2024-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0068_alter_customer_customer_code_edite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
                ('complaint_details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الشكوى')),
                ('proposed_solution', models.TextField(blank=True, null=True, verbose_name='الحل المقترح')),
                ('action_status', models.CharField(blank=True, choices=[('قيد التنفيذ', 'قيد التنفيذ'), ('تم التنفيذ', 'تم التنفيذ'), ('مرفوض', 'مرفوض'), ('تحت الاعتماد', 'تحت الاعتماد')], default='قيد التنفيذ', max_length=50, null=True, verbose_name='حالة الإجراء')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='الحل')),
            ],
            options={
                'verbose_name': 'جدول الإجراءات التصحيحية',
                'verbose_name_plural': 'جدول الإجراءات التصحيحية',
            },
        ),
        migrations.AddField(
            model_name='design_and_printing_specifications',
            name='approved_montage_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='العدد في المونتاج المعتمد'),
        ),
        migrations.AddField(
            model_name='design_and_printing_specifications',
            name='approved_montage_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس المونتاج المعتمد'),
        ),
    ]
