# Generated by Django 4.2.9 on 2024-03-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0069_correctiveactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_CorrectiveActions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.correctiveactions'),
        ),
    ]
