# Generated by Django 4.2.9 on 2024-03-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0070_remove_product_product_design_and_printing_specifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Design_and_printing_specifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.design_and_printing_specifications'),
        ),
    ]
