# Generated by Django 4.2.9 on 2024-03-31 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0071_product_product_design_and_printing_specifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_CorrectiveActions',
        ),
        migrations.AddField(
            model_name='correctiveactions',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Products', to='Work_Orders.product'),
        ),
    ]
