# Generated by Django 4.2.9 on 2024-04-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0072_remove_product_product_correctiveactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design_and_printing_specifications',
            name='pro_design_ditals',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='تفاصيل التصميم '),
        ),
    ]
