# Generated by Django 4.2.9 on 2024-07-24 14:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Work_Orders', '0075_alter_product_customer_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer_representative',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('د/عمروالباز', 'د/عمروالباز'), ('ا/عمرو احمد', 'ا/عمرو احمد'), ('م/كريم عبد الغنى', 'م/كريم عبد الغنى'), ('أخرى', 'أخرى')], default='أخرى', max_length=100, verbose_name='ممثل  العميل'),
        ),
    ]
