# Generated by Django 4.1.4 on 2023-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0003_alter_supplier_address_alter_supplier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='quntity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الكميه'),
        ),
    ]
