# Generated by Django 4.1.4 on 2023-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0004_alter_iteam_code_alter_iteam_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='code',
            field=models.CharField(editable=False, max_length=100, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='name',
            field=models.CharField(editable=False, max_length=100, verbose_name='الاسم'),
        ),
    ]
