# Generated by Django 4.1.4 on 2023-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0005_alter_iteam_code_alter_iteam_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iteam',
            name='quntity',
        ),
    ]
