# Generated by Django 4.1.4 on 2023-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0008_in_stock_pako_in_stock_pukker_in_stock_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='code',
            field=models.CharField(default='00-00-00-00-000', max_length=100, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='name',
            field=models.CharField(default='الاسم الكامل للصنف ', max_length=100, unique=True, verbose_name='الاسم'),
        ),
    ]
