# Generated by Django 4.1.4 on 2023-02-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0008_in_stock_pako_in_stock_pukker_in_stock_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pako',
            name='grams',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pako',
            name='linght',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pako',
            name='weaight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pako',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pukker',
            name='weaight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pukker',
            name='width',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='grams',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='linght',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='weaight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sub',
            name='width',
            field=models.FloatField(default=0),
        ),
    ]
