# Generated by Django 4.1.4 on 2023-02-02 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0010_remove_pako_grams_remove_sub_grams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='iteam',
        ),
    ]
