# Generated by Django 4.1.4 on 2023-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0011_remove_in_stock_iteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gram_categore',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gram_categore',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
