# Generated by Django 4.1.4 on 2023-02-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0012_alter_gram_categore_code_alter_gram_categore_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='linght',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(default=0, max_length=100)),
                ('code', models.CharField(default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(max_length=100)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.RenameField(
            model_name='pukker',
            old_name='width',
            new_name='total_linght',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='linght',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='width',
        ),
        migrations.RemoveField(
            model_name='pukker',
            name='code',
        ),
        migrations.RemoveField(
            model_name='pukker',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='code',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='linght',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='width',
        ),
        migrations.AlterField(
            model_name='gram_categore',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='gram_categore',
            name='name',
            field=models.FloatField(max_length=100),
        ),
        migrations.AddField(
            model_name='iteam',
            name='linght',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.linght'),
        ),
        migrations.AddField(
            model_name='iteam',
            name='width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.width'),
        ),
    ]
