# Generated by Django 4.1.4 on 2023-02-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0010_alter_iteam_code_alter_iteam_name'),
        ('storge', '0016_alter_out_stock_date'),
    ]

    operations = [
    ]
