# Generated by Django 4.1.4 on 2023-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0017_merge_20230206_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='out_stock',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
