# Generated by Django 4.1.4 on 2023-02-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0018_alter_in_stock_date_alter_out_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_stock',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='quntity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pako',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pako',
            name='weaight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pukker',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pukker',
            name='total_linght',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pukker',
            name='weaight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='weaight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
