# Generated by Django 4.1.4 on 2023-02-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0019_alter_in_stock_date_alter_in_stock_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pukker',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
