# Generated by Django 4.1.4 on 2023-02-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0020_alter_pukker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pukker',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
