# Generated by Django 4.1.4 on 2023-02-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0021_alter_pukker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteam',
            name='gram_categore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='linght',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
