# Generated by Django 4.1.4 on 2023-02-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0022_alter_iteam_gram_categore_alter_iteam_linght_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='pako',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='pukker',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='quntity',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='sub',
        ),
        migrations.AddField(
            model_name='in_stock',
            name='sheet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='weaight',
            field=models.FloatField(default=0, max_length=100, verbose_name='الوزن'),
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='price',
            field=models.FloatField(default=0, max_length=100, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='gram_categore',
            field=models.IntegerField(default='000'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='linght',
            field=models.IntegerField(default='0000'),
        ),
        migrations.AlterField(
            model_name='iteam',
            name='width',
            field=models.IntegerField(default='0000'),
        ),
    ]
