# Generated by Django 4.1.4 on 2023-02-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0023_remove_in_stock_pako_remove_in_stock_pukker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_stock',
            name='iteam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storge.iteam'),
            preserve_default=False,
        ),
    ]
