# Generated by Django 4.1.4 on 2023-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0024_in_stock_iteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_stock',
            name='code',
            field=models.CharField(default='00-00-00-00-000000000000-0000', max_length=100, verbose_name='الكود'),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='name',
            field=models.CharField(default='اذن توريد', max_length=100, verbose_name='الاسم'),
        ),
    ]
