# Generated by Django 4.1.4 on 2023-02-09 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0025_in_stock_code_in_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='code',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='iteam',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='weaight',
        ),
        migrations.CreateModel(
            name='In_stoke_detals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weaight', models.FloatField(default=0, max_length=100, verbose_name='الوزن')),
                ('sheet', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0, max_length=100, verbose_name='السعر')),
                ('name', models.CharField(default='اذن توريد', max_length=100, verbose_name='الاسم')),
                ('code', models.CharField(default='00-00-00-00-000000000000-0000', max_length=100, verbose_name='الكود')),
                ('iteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.iteam')),
            ],
        ),
    ]
