# Generated by Django 4.1.4 on 2023-02-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0026_remove_in_stock_code_remove_in_stock_iteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_stoke_detals',
            name='in_stock',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storge.in_stock'),
            preserve_default=False,
        ),
    ]
