# Generated by Django 4.1.4 on 2023-02-09 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0027_in_stoke_detals_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='in_stoke_detals',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='in_stoke_detals',
            name='supplier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storge.supplier'),
            preserve_default=False,
        ),
    ]
