# Generated by Django 4.1.4 on 2023-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0028_remove_in_stoke_detals_in_stock_in_stoke_detals_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_stoke_detals',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='in_stoke_detals',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='in_stoke_detals',
            name='weaight',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True, verbose_name='الوزن'),
        ),
    ]
