# Generated by Django 4.1.4 on 2023-02-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0029_alter_in_stoke_detals_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_stoke_detals',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
