# Generated by Django 4.1.4 on 2023-02-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0031_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
