# Generated by Django 4.1.4 on 2023-02-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0032_alter_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
