# Generated by Django 4.1.4 on 2023-02-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0033_alter_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
