# Generated by Django 4.1.4 on 2023-02-16 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storge', '0037_remove_out_stock_in_stock_remove_out_stock_iteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='out_stock',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='out_stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='out_stock',
            name='in_stock_detals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.in_stoke_detals', verbose_name='الاصناف'),
        ),
        migrations.AlterField(
            model_name='out_stock',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الشيت'),
        ),
    ]
