# Generated by Django 4.1.4 on 2023-02-16 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0038_customer_user_alter_out_stock_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='supplier',
        ),
        migrations.AddField(
            model_name='in_stock',
            name='code',
            field=models.CharField(default='00-00-00-00-000000000000-0000', max_length=100, verbose_name='الكود'),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='iteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.iteam', verbose_name='الصنف'),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='name',
            field=models.CharField(default='اذن توريد', max_length=100, verbose_name='الاسم'),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='price',
            field=models.FloatField(default=0, max_length=100, verbose_name='السعر'),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='in_stock',
            name='weaight',
            field=models.FloatField(blank=True, default=0, max_length=100, null=True, verbose_name='الوزن'),
        ),
        migrations.CreateModel(
            name='InStockNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('number', models.IntegerField(default=0, verbose_name='رقم امر التوريد ')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.AddField(
            model_name='in_stock',
            name='InStockNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.instocknumber', verbose_name='رقم امر التوريد'),
        ),
    ]
