# Generated by Django 4.1.4 on 2023-02-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0039_remove_in_stock_supplier_in_stock_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='in_stock',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storge.supplier', verbose_name='المورد'),
            preserve_default=False,
        ),
    ]
