# Generated by Django 4.1.4 on 2023-02-16 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0040_in_stock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='InStockNumber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storge.instocknumber', verbose_name='رقم امر التوريد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='in_stock',
            name='iteam',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storge.iteam', verbose_name='الصنف'),
            preserve_default=False,
        ),
    ]
