# Generated by Django 4.1.4 on 2023-02-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0041_remove_in_stock_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instocknumber',
            name='states',
            field=models.BooleanField(default=False, verbose_name='الحاله'),
        ),
    ]
