# Generated by Django 4.1.4 on 2023-02-22 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0042_instocknumber_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instocknumber',
            old_name='states',
            new_name='status',
        ),
    ]
