# Generated by Django 4.1.4 on 2023-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0043_rename_states_instocknumber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instocknumber',
            name='status',
            field=models.CharField(choices=[('تعديل', 'تعديل'), ('نهائى', 'نهائى')], default='تعديل', max_length=100, verbose_name='الحاله'),
        ),
    ]
