# Generated by Django 4.1.4 on 2023-02-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0045_alter_instocknumber_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='in_stock',
            old_name='InStockNumber',
            new_name='in_stocknumber',
        ),
    ]
