# Generated by Django 4.1.4 on 2023-02-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0046_rename_instocknumber_in_stock_in_stocknumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_stock',
            name='sheet',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='الورقه'),
        ),
        migrations.CreateModel(
            name='Out_StockNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='التاريخ')),
                ('number', models.IntegerField(default=0, verbose_name='رقم امر الصرف ')),
                ('status', models.CharField(choices=[('تعديل', 'تعديل'), ('نهائي', 'نهائي')], default='تعديل', max_length=100, verbose_name='الحاله')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storge.customer', verbose_name='العميل')),
            ],
        ),
    ]
