# Generated by Django 4.1.4 on 2023-03-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0047_alter_in_stock_sheet_out_stocknumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_stock',
            name='in_stock_detals',
        ),
        migrations.AddField(
            model_name='out_stock',
            name='in_stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storge.in_stock', verbose_name='الصنف'),
            preserve_default=False,
        ),
    ]
