# Generated by Django 4.1.4 on 2023-03-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0048_remove_out_stock_in_stock_detals_out_stock_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_stock',
            name='code',
        ),
        migrations.AddField(
            model_name='out_stock',
            name='out_stocknumber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='storge.out_stocknumber', verbose_name='رقم امر الصرف'),
            preserve_default=False,
        ),
    ]
