# Generated by Django 4.1.4 on 2023-03-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0050_remove_out_stock_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_stock',
            name='total_sheet',
            field=models.IntegerField(default=0, verbose_name='الشيت الكلي'),
        ),
        migrations.AddField(
            model_name='out_stock',
            name='total_weight',
            field=models.FloatField(default=0, max_length=100, verbose_name='الوزن الكلي'),
        ),
    ]
