# Generated by Django 4.1.4 on 2023-03-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0051_out_stock_total_sheet_out_stock_total_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='out_stock',
            name='total_sheet',
        ),
        migrations.RemoveField(
            model_name='out_stock',
            name='total_weight',
        ),
    ]
