# Generated by Django 4.1.4 on 2023-03-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0053_in_stock_total_sheet_in_stock_total_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stock',
            name='total_sheet',
        ),
        migrations.RemoveField(
            model_name='in_stock',
            name='total_weight',
        ),
    ]
