# Generated by Django 4.1.4 on 2023-04-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0054_remove_in_stock_total_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='code',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='iteam',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='name',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='price',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='in_stoke_detals',
            name='weaight',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='iteam',
        ),
        migrations.RemoveField(
            model_name='pako',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='pukker',
            name='iteam',
        ),
        migrations.RemoveField(
            model_name='pukker',
            name='number',
        ),
        migrations.RemoveField(
            model_name='pukker',
            name='total_linght',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='iteam',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='sheet',
        ),
    ]
