# Generated by Django 4.1.4 on 2023-04-06 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storge', '0055_remove_in_stoke_detals_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='out_stock',
            name='iteam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storge.iteam', verbose_name='الصنف'),
        ),
    ]
