# Generated by Django 4.0 on 2022-09-10 11:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Work_Orders', '0032_alter_design_and_printing_specifications_pro_old_execution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_and_cardboard_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CARD_Work_order_number_in_chart', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم امر الشغل فى  الشيتر')),
                ('CARD_Supplier', models.CharField(blank=True, max_length=50, null=True, verbose_name='المورد')),
                ('CARD_Paper_type_and_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الورق ومقاسة')),
                ('CARD_note_Paper_type_and_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات على نوع الورق ومقاسة')),
                ('CARD_Number', models.CharField(blank=True, max_length=50, null=True, verbose_name='العدد')),
                ('CARD_Cut_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس القطع')),
                ('CARD_fiber_direction', models.CharField(blank=True, max_length=50, null=True, verbose_name='اتجاه الالياف')),
                ('CARD_Total_cut_and_fiber', models.CharField(blank=True, max_length=70, null=True, verbose_name=' الاجمالى للقطع والالياف')),
                ('CARD_Gross_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن القائم')),
                ('CARD_Net_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن الصافى')),
                ('CARD_Total_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن الاجمالى')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ord_Created_Dt', models.DateTimeField(auto_now_add=True)),
                ('Order_Details', models.TextField(max_length=4000)),
                ('Ord_work_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم امر الشغل')),
                ('customer_representative', models.CharField(blank=True, max_length=50, null=True, verbose_name='ممثل العميل')),
                ('Ord_Required_quantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='الكمية المطلوبة')),
                ('Ord_import_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم امر التورد')),
                ('Ord_Operation_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('مكررة', 'مكررة'), ('جديدة', 'جديدة'), ('تعديل', 'تعديل')], max_length=17, null=True, verbose_name='نوع العملية')),
                ('Ord_Operation_modification_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع التعديل')),
                ('Ord_Length', models.CharField(blank=True, max_length=50, null=True, verbose_name='الطول')),
                ('Ord_Width', models.CharField(blank=True, max_length=50, null=True, verbose_name='العرض')),
                ('Ord_Height', models.CharField(blank=True, max_length=50, null=True, verbose_name='الارتفاع')),
                ('Ord_montage_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس المونتاج')),
                ('Ord_zincs', models.CharField(blank=True, max_length=50, null=True, verbose_name='الزنكات')),
                ('Ord_Number_the_montage', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد فى المونتاج')),
                ('Ord_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='فورمة')),
                ('Ord_number_of_faces', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الاوجه')),
                ('Ord_the_machine', models.CharField(blank=True, max_length=50, null=True, verbose_name='الماكينة')),
                ('Ord_colors_are_picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوان  صورة')),
                ('Ord_custom_colors', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوان مخصوصة')),
                ('Ord_print_note', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات الطباعة')),
                ('Ord_cellophane_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع السيلوفان')),
                ('Ord_face_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الوجه')),
                ('Ord_Maiden_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس البكر')),
                ('Ord_Other_services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ورنيش مائى', 'ورنيش مائى'), ('يوفى ', 'يوفى '), ('اخرى', 'اخرى')], max_length=21, null=True, verbose_name='خدمات اخرى')),
                ('Ord_Description_services', models.CharField(blank=True, max_length=50, null=True, verbose_name='وصف الخدمات')),
                ('Ord_Notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات')),
                ('Ord_Breaking_services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('فورمه جديد', 'فورمه جديد'), ('فورمه قديمه ', 'فورمه قديمه '), ('شباك جديد ', 'شباك جديد '), ('شباك قديم ', 'شباك قديم ')], max_length=45, null=True, verbose_name='خدمات التكسير')),
                ('Ord_Chop_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود/عدد الفورمه')),
                ('Ord_form_of', models.CharField(blank=True, max_length=50, null=True, verbose_name='فورمه من')),
                ('Ord_Machine', models.CharField(blank=True, max_length=50, null=True, verbose_name='الماكينة')),
                ('Ord_Number_Reg', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الريج')),
                ('Ord_Attachments', models.CharField(blank=True, max_length=50, null=True, verbose_name='المرفقات')),
                ('Ord_Note_Breaking', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات التكسير')),
                ('Ord_Others', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('كفراج', 'كفراج'), ('تنظيف ', 'تنظيف ')], max_length=12, null=True, verbose_name='اخرى')),
                ('Ord_Gluing', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('آلى', 'آلى'), ('يدووى ', 'يدووى ')], max_length=10, null=True, verbose_name='تلزيق ')),
                ('Ord_Note_Gluing', models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات التلزيق ')),
                ('Ord_Binding_Gluing', models.CharField(blank=True, max_length=50, null=True, verbose_name='التجليد')),
                ('Ord_number_corners', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الاركان')),
                ('Ord_Gluing_Description', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوصف')),
                ('Ord_machine_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الماكينة')),
                ('Ord_Complete_Product', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('باندات', 'باندات'), ('استيك', 'استيك'), ('يدوى', 'يدوى')], max_length=17, null=True, verbose_name='المنتج التام')),
                ('Ord_number_pandas', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الباندات')),
                ('Ord_Packing', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('صناديق', 'صناديق'), (' كفراج/ورق لف', ' كفراج/ورق لف'), ('اكياس', 'اكياس')], max_length=26, null=True, verbose_name='التغليف')),
                ('Ord_number_pacu', models.CharField(blank=True, max_length=50, null=True, verbose_name='العدد الباكو')),
                ('Ord_Required_materials', models.CharField(blank=True, max_length=150, null=True, verbose_name='المواد المطلوبة')),
                ('Ord_Delivery_Instructions', models.CharField(blank=True, max_length=150, null=True, verbose_name='تعليمات التسليم')),
                ('Ord_Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='auth.user')),
                ('Ord_Cust_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Work_Orders.customer', verbose_name='اسم العميل')),
                ('Ord_Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Work_Orders.product')),
            ],
        ),
    ]
