# Generated by Django 4.0 on 2022-09-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ord_Annexes_design_data',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المرفقات للتصميم والتجهيزات الفنيه'),
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_Other_supplies',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لوازم اخرى'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Details',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='تفاصيل الطلب'),
        ),
    ]
