# Generated by Django 4.0 on 2022-09-11 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Order', '0002_order_ord_annexes_design_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_Created_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='auth.user'),
        ),
    ]
