# Generated by Django 4.0 on 2022-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_paper_and_cardboard_data_card_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ord_code_Edited',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Details',
            field=models.TextField(blank=True, max_length=40, null=True, verbose_name='تفاصيل الطلب'),
        ),
    ]
