# Generated by Django 4.0 on 2022-09-12 07:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_ord_code_edited_alter_order_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_Breaking_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('فورمه جديد', 'فورمه جديد'), ('فورمه قديمه', 'فورمه قديمه'), ('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=42, null=True, verbose_name='خدمات التكسير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Gluing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('آلى', 'آلى'), ('يدووى', 'يدووى')], max_length=9, null=True, verbose_name='تلزيق '),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Note_Gluing',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ملاحظات التلزيق'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Other_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ورنيش مائى', 'ورنيش مائى'), ('يوفى', 'يوفى'), ('اخرى', 'اخرى')], max_length=20, null=True, verbose_name='خدمات اخرى'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Others',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('كفراج', 'كفراج'), ('تنظيف', 'تنظيف')], max_length=11, null=True, verbose_name='اخرى'),
        ),
    ]
