# Generated by Django 4.0 on 2022-09-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_alter_order_ord_breaking_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Ord_Cust_Name',
            new_name='Ord_Customer_Name',
        ),
    ]
