# Generated by Django 4.0 on 2022-09-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_rename_ord_cust_name_order_ord_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_code_Edited',
            field=models.CharField(default='', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_work_order_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='رقم امر الشغل'),
            preserve_default=False,
        ),
    ]
