# Generated by Django 4.0 on 2022-09-19 10:15

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0010_order_ord_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_representative',
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Breaking_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('فورمه جديد', 'فورمه جديد'), ('فورمه قديمه', 'فورمه قديمه'), ('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=200, null=True, verbose_name='خدمات التكسير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Complete_Product',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('باندات', 'باندات'), ('استيك', 'استيك'), ('يدوى', 'يدوى')], max_length=100, null=True, verbose_name='المنتج التام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Gluing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('آلى', 'آلى'), ('يدوى', 'يدوى')], max_length=100, null=True, verbose_name='تلزيق '),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Operation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('مكررة', 'مكررة'), ('جديدة', 'جديدة'), ('تعديل', 'تعديل')], max_length=50, null=True, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Other_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ورنيش مائى', 'ورنيش مائى'), ('يوفى', 'يوفى'), ('اخرى', 'اخرى')], max_length=100, null=True, verbose_name='خدمات اخرى'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Others',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('كفراج', 'كفراج'), ('تنظيف', 'تنظيف')], max_length=100, null=True, verbose_name='اخرى'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Packing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('صناديق', 'صناديق'), (' كفراج/ورق لف', ' كفراج/ورق لف'), ('اكياس', 'اكياس')], max_length=100, null=True, verbose_name='التغليف'),
        ),
    ]
