# Generated by Django 4.0 on 2022-09-19 11:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0011_remove_order_customer_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ord_Breaking_services_two',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=100, null=True, verbose_name='خدمات التكسير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Breaking_services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('فورمه جديد', 'فورمه جديد'), ('فورمه قديمه', 'فورمه قديمه')], max_length=100, null=True, verbose_name='خدمات التكسير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Packing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('صناديق', 'صناديق'), ('كفراج/ورق لف', 'كفراج/ورق لف'), ('اكياس', 'اكياس')], max_length=100, null=True, verbose_name='التغليف'),
        ),
    ]
