# Generated by Django 4.0 on 2022-09-19 15:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_alter_order_ord_breaking_services_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_Breaking_services_two',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=100, null=True, verbose_name='خدمات التكسير'),
        ),
    ]
