# Generated by Django 4.0 on 2022-09-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_alter_order_ord_breaking_services_two'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ord_Breaking_services_two',
        ),
    ]
