# Generated by Django 4.0 on 2022-09-20 10:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_order_ord_breaking_services_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ord_code_pro',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_code_pro_update',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Breaking_services_two',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=100, null=True, verbose_name='خدمات التكسير'),
        ),
    ]
