# Generated by Django 4.0 on 2022-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_order_ord_code_pro_order_ord_code_pro_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_code_pro',
            field=models.CharField(default='', editable=False, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_code_pro_update',
            field=models.CharField(default='', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
