# Generated by Django 4.0 on 2022-09-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0019_alter_order_ord_code_pro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ord_code_pro',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Ord_code_pro_update',
        ),
    ]
