# Generated by Django 4.0 on 2022-09-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_remove_order_ord_code_pro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Ord_Height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Ord_Length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Ord_Width',
        ),
    ]
