# Generated by Django 4.0 on 2022-09-24 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Order', '0021_remove_order_ord_height_remove_order_ord_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_states',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='تم التعديل بواسطة'),
        ),
        migrations.AddField(
            model_name='order_states',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاريخ التعديل'),
        ),
    ]
