# Generated by Django 4.0 on 2022-09-24 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Order', '0022_order_states_update_by_order_states_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_states',
            name='update_by',
        ),
        migrations.RemoveField(
            model_name='order_states',
            name='update_date',
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Orders_updated', to='auth.user'),
        ),
    ]
