# Generated by Django 4.0 on 2022-09-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_remove_order_states_update_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Number_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العدد'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المورد'),
        ),
    ]
