# Generated by Django 4.0 on 2022-09-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0025_paper_and_cardboard_data_card_number_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Gross_weight_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن القائم'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Net_weight_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='الوزن الصافى'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Number_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Number_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Number_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='العدد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Paper_type_and_size_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='نوع الورق ومقاسة'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='المورد'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Supplier_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='المورد'),
        ),
    ]
