# Generated by Django 4.0 on 2022-09-26 12:03

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0026_alter_paper_and_cardboard_data_card_gross_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_and_cardboard_data',
            name='CARD_Total_cut_and_fiber',
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_colors_nember',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الالوان'),
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_type_print',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ربع', 'ربع'), ('نص', 'نص'), ('فرخ ', 'فرخ ')], max_length=11, null=True, verbose_name=' الطباعة'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Grame',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='جرام'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Grame_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='جرام'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Grame_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='جرام'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_Grame_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='جرام'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_long_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عدد الطول'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_long_number_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عدد الطول'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_long_number_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عدد الطول'),
        ),
        migrations.AddField(
            model_name='paper_and_cardboard_data',
            name='CARD_long_number_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='عدد الطول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Annexes_design_data',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المرفقات للتصميم والتجهيزات الفنيه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Attachments',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المرفقات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Delivery_Instructions',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='تعليمات التسليم'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Description_services',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='وصف الخدمات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Gluing_Description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Note_Breaking',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات التكسير'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Notes',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Operation_modification_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع التعديل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Other_supplies',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='لوازم اخرى'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_Required_materials',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='المواد المطلوبة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_number_pacu',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='العدد الباكو'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_print_note',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات الطباعة'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Cut_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس قص السكينه'),
        ),
        migrations.AlterField(
            model_name='paper_and_cardboard_data',
            name='CARD_Total_weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='العددالاجمالى'),
        ),
    ]
