# Generated by Django 4.0 on 2022-10-04 14:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0028_remove_order_ord_binding_gluing_order_states_orders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_states',
            name='orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_type_print',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ربع', 'ربع'), ('نص', 'نص'), ('فرخ', 'فرخ')], max_length=50, null=True, verbose_name=' الطباعة'),
        ),
    ]
