# Generated by Django 4.0 on 2022-10-13 10:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0030_alter_order_ord_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_Others',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('كفراج', 'كفراج'), ('تنظيف', 'تنظيف'), ('اخرى', 'اخرى')], max_length=100, null=True, verbose_name='اخرى'),
        ),
    ]
