# Generated by Django 4.0 on 2023-04-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0031_alter_order_ord_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_Created_Dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
