# Generated by Django 4.0 on 2023-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0032_alter_order_ord_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_states',
            name='name',
            field=models.CharField(blank=True, choices=[('', ''), ('Arial', 'Arial'), ('Times New Roman', 'Times New Roman'), ('Verdana', 'Verdana'), ('Helvetica', 'Helvetica'), ('Courier New', 'Courier New'), ('Tahoma', 'Tahoma'), ('Georgia', 'Georgia'), ('Calibri', 'Calibri'), ('Palatino', 'Palatino'), ('Impact', 'Impact'), ('Comic Sans MS', 'Comic Sans MS'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Font Awesome 5 Free', 'Font Awesome 5 Free'), ('auto', 'Auto'), ('cursive', 'Cursive'), ('emoji', 'Emoji'), ('fangsong', 'Fangsong'), ('fantasy', 'Fantasy'), ('inherit', 'Inherit'), ('initial', 'Initial'), ('math', 'Math'), ('monospace', 'Monospace'), ('none', 'None'), ('revert', 'Revert'), ('sans-serif', 'Sans-serif'), ('serif', 'Serif'), ('system-ui', 'System UI'), ('ui-monospace', 'UI Monospace'), ('ui-rounded', 'UI Rounded'), ('ui-sans-serif', 'UI Sans-serif')], max_length=50, null=True, verbose_name='الاسم'),
        ),
    ]
