# Generated by Django 4.2.9 on 2024-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0033_alter_order_states_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_states',
            name='name',
            field=models.CharField(blank=True, choices=[('', ''), ('جديد', 'جديد'), ('تصميم', 'تصميم'), ('مونتاج', 'مونتاج'), ('سلوفان', 'سلوفان'), ('خدمات طباعة ورنيش/يوفي', 'خدمات طباعة ورنيش/يوفي'), ('خدمات طباعة خارجي', 'خدمات طباعة خارجي'), ('جديد', 'جديد'), ('تصميم', 'تصميم'), ('مونتاج', 'مونتاج'), ('Calibri', 'Calibri'), ('Palatino', 'Palatino'), ('Impact', 'Impact'), ('Comic Sans MS', 'Comic Sans MS'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Font Awesome 5 Free', 'Font Awesome 5 Free'), ('auto', 'Auto'), ('cursive', 'Cursive'), ('emoji', 'Emoji'), ('fangsong', 'Fangsong'), ('fantasy', 'Fantasy'), ('inherit', 'Inherit'), ('initial', 'Initial'), ('math', 'Math'), ('monospace', 'Monospace'), ('none', 'None'), ('revert', 'Revert'), ('sans-serif', 'Sans-serif'), ('serif', 'Serif'), ('system-ui', 'System UI'), ('ui-monospace', 'UI Monospace'), ('ui-rounded', 'UI Rounded'), ('ui-sans-serif', 'UI Sans-serif')], max_length=50, null=True, verbose_name='الاسم'),
        ),
    ]
