# Generated by Django 4.2.9 on 2024-01-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0038_alter_order_states_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_states',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.order_states', verbose_name='المرحلة'),
            preserve_default=False,
        ),
    ]
