# Generated by Django 4.2.9 on 2024-04-24 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0043_alter_order_ord_breaking_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RDD', models.DateField()),
                ('EDD', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Ord_delivery_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.orderdeliverydate'),
        ),
    ]
