# Generated by Django 4.2.9 on 2024-05-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0045_alter_orderdeliverydate_edd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Ord_custom_colors',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='الوان مخصوصة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='Ord_form_of',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='فورمه من'),
        ),
    ]
