# Generated by Django 4.2.9 on 2024-07-06 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Work_Orders', '0074_representative_customer_representative'),
        ('Order', '0048_alter_order_states_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('Ord_code_Edited', models.CharField(editable=False, max_length=50)),
                ('Ord_Created_Dt', models.DateField(blank=True, editable=False)),
                ('Order_Details', models.TextField(blank=True, max_length=40, null=True, verbose_name='تفاصيل الطلب')),
                ('Ord_work_order_number', models.CharField(db_index=True, max_length=50, verbose_name='رقم امر الشغل')),
                ('Ord_Required_quantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='الكمية المطلوبة')),
                ('Ord_import_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم امر التورد')),
                ('Ord_Operation_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('مكررة', 'مكررة'), ('جديدة', 'جديدة'), ('تعديل', 'تعديل')], max_length=50, null=True, verbose_name='نوع العملية')),
                ('Ord_Operation_modification_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع التعديل')),
                ('Ord_montage_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس المونتاج')),
                ('Ord_zincs', models.CharField(blank=True, max_length=50, null=True, verbose_name='الزنكات')),
                ('Ord_Number_the_montage', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد فى المونتاج')),
                ('Ord_form', models.CharField(blank=True, max_length=50, null=True, verbose_name='فورمة')),
                ('Ord_Annexes_design_data', models.CharField(blank=True, max_length=250, null=True, verbose_name='المرفقات للتصميم والتجهيزات الفنيه')),
                ('Ord_Other_supplies', models.CharField(blank=True, max_length=250, null=True, verbose_name='لوازم اخرى')),
                ('Ord_type_print', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('ربع', 'ربع'), ('نص', 'نص'), ('فرخ', 'فرخ')], max_length=50, null=True, verbose_name=' الطباعة')),
                ('Ord_colors_nember', models.CharField(blank=True, max_length=10, null=True, verbose_name='عدد الالوان')),
                ('Ord_number_of_faces', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الاوجه')),
                ('Ord_the_machine', models.CharField(blank=True, max_length=50, null=True, verbose_name='الماكينة')),
                ('Ord_colors_are_picture', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوان  صورة')),
                ('Ord_custom_colors', models.CharField(blank=True, max_length=500, null=True, verbose_name='الوان مخصوصة')),
                ('Ord_print_note', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات الطباعة')),
                ('Ord_cellophane_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع السيلوفان')),
                ('Ord_face_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الوجه')),
                ('Ord_Maiden_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='مقاس البكر')),
                ('Ord_Other_services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('ورنيش مائى', 'ورنيش مائى'), ('يوفى', 'يوفى'), ('ورنيش دهنى', 'ورنيش دهنى'), ('يوفى ثم ورنيش', 'يوفى ثم ورنيش'), ('سبوت', 'سبوت'), ('اخرى', 'اخرى')], max_length=100, null=True, verbose_name='خدمات اخرى')),
                ('Ord_Description_services', models.CharField(blank=True, max_length=250, null=True, verbose_name='وصف الخدمات')),
                ('Ord_Notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات')),
                ('Ord_Breaking_services', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('فورمه جديد', 'فورمه جديد'), ('فورمه قديمه', 'فورمه قديمه')], max_length=100, null=True, verbose_name='خدمات التكسير')),
                ('Ord_Breaking_services_two', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('شباك جديد', 'شباك جديد'), ('شباك قديم', 'شباك قديم')], max_length=100, null=True, verbose_name='خدمات التكسير')),
                ('Ord_Chop_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود/عدد الفورمه')),
                ('Ord_form_of', models.CharField(blank=True, max_length=500, null=True, verbose_name='فورمه من')),
                ('Ord_Machine', models.CharField(blank=True, max_length=50, null=True, verbose_name='الماكينة')),
                ('Ord_Number_Reg', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الريج')),
                ('Ord_Attachments', models.CharField(blank=True, max_length=250, null=True, verbose_name='المرفقات')),
                ('Ord_Note_Breaking', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات التكسير')),
                ('Ord_Others', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('كفراج', 'كفراج'), ('تنظيف', 'تنظيف'), ('اخرى', 'اخرى')], max_length=100, null=True, verbose_name='اخرى')),
                ('Ord_Gluing', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('آلى', 'آلى'), ('يدوى', 'يدوى'), ('تجليد', 'تجليد')], max_length=100, null=True, verbose_name='تلزيق ')),
                ('Ord_Note_Gluing', models.CharField(blank=True, max_length=250, null=True, verbose_name='ملاحظات التلزيق')),
                ('Ord_number_corners', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الاركان')),
                ('Ord_Gluing_Description', models.CharField(blank=True, max_length=250, null=True, verbose_name='الوصف')),
                ('Ord_machine_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الماكينة')),
                ('Ord_Complete_Product', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('باندات', 'باندات'), ('استيك', 'استيك'), ('يدوى', 'يدوى'), ('اخرى', 'اخرى')], max_length=100, null=True, verbose_name='المنتج التام')),
                ('Ord_number_pandas', models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد/الباندات')),
                ('Ord_Packing', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', ''), ('صناديق', 'صناديق'), ('كرافت/ورق لف', 'كرافت/ورق لف'), ('اكياس', 'اكياس')], max_length=100, null=True, verbose_name='التغليف')),
                ('Ord_number_pacu', models.CharField(blank=True, max_length=15, null=True, verbose_name='العدد/الباكو')),
                ('Ord_Required_materials', models.CharField(blank=True, max_length=250, null=True, verbose_name='المواد المطلوبة')),
                ('Ord_Delivery_Instructions', models.CharField(blank=True, max_length=500, null=True, verbose_name='تعليمات التسليم')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Ord_Created_By', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('Ord_Customer_Name', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Work_Orders.customer', verbose_name='اسم العميل')),
                ('Ord_Product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Work_Orders.product')),
                ('Ord_delivery_date', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Order.orderdeliverydate')),
                ('Ord_states', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Order.order_states', verbose_name='المرحلة')),
                ('Ord_updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical order',
                'verbose_name_plural': 'historical orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
